### ISSUE TITLE
Create lab input data input page 

### ISSUE THREAD

**Issue by dalanmiller** [dalanmiller/MooData-App#9]

**Comment by mishra123** [comment]
Hi Daniel..I am almost done with the input page..But do we have some standard CSS to give styling to the page?

**Comment by dalanmiller** [comment]
Yes just use bootstrap.css which should be sufficient for now.

**Comment by mishra123** [comment]
Ok..

**Comment by mishra123** [comment]
As all the values are integer, so do we need to set some alert if user enter some text or string..?

**Comment by dalanmiller** [comment]
Check this out.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms_in_HTML

I think the input elements should maybe have the `type=number` attribute
set. But read that article to confirm.

**Comment by mishra123** [comment]
Hi Daniel...How can I send the files here..?

**Comment by dalanmiller** [comment]
Since that is actually for the API portion, you can add the file to the
MooData-API repository under the 'templates' folder.

2013/11/19 Anoop Mishra notifications@github.com

**Comment by dalanmiller** [comment]
Hey Noop, 

I'm going to close this since you finished this, but just going to integrate it into the dashboard.html
